# Generated by Django 6.0 on 2026-01-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxApp', '0002_country_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='stateId',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='countryId',
            new_name='country',
        ),
    ]
