# Generated by Django 6.0 on 2025-12-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productApp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='test.png', upload_to='images'),
            preserve_default=False,
        ),
    ]
