# Generated by Django 6.0 on 2025-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
