# Generated by Django 6.0.1 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sName',
            field=models.CharField(default='default0', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sPhone',
            field=models.IntegerField(default=0),
        ),
    ]
