# Generated by Django 6.0 on 2025-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(default='test', max_length=25, null=True),
        ),
    ]
